language: node_js
node_js:
  - '8'
  - '6'
script:
  - npm run test
  - npm run build
after_script: npm run cover && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
branches:
  only:
    - master
